// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTlXo93RFQBxqv2CWrxFWSY6nKjXlEF3Q',
    appId: '1:170567973902:web:c1a274e5a757c41238505f',
    messagingSenderId: '170567973902',
    projectId: 'hallo-611ac',
    authDomain: 'hallo-611ac.firebaseapp.com',
    storageBucket: 'hallo-611ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5vLfP-zCxBxjHjtlBM3snnZtFO0iaax4',
    appId: '1:170567973902:android:6ed0b7cf9baea81d38505f',
    messagingSenderId: '170567973902',
    projectId: 'hallo-611ac',
    storageBucket: 'hallo-611ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWvOn3hbMdRAwIKeKpMoXASl6OvI7Ds6k',
    appId: '1:170567973902:ios:58a42fa6bf9daf8338505f',
    messagingSenderId: '170567973902',
    projectId: 'hallo-611ac',
    storageBucket: 'hallo-611ac.firebasestorage.app',
    iosBundleId: 'com.example.tichafasta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWvOn3hbMdRAwIKeKpMoXASl6OvI7Ds6k',
    appId: '1:170567973902:ios:58a42fa6bf9daf8338505f',
    messagingSenderId: '170567973902',
    projectId: 'hallo-611ac',
    storageBucket: 'hallo-611ac.firebasestorage.app',
    iosBundleId: 'com.example.tichafasta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTlXo93RFQBxqv2CWrxFWSY6nKjXlEF3Q',
    appId: '1:170567973902:web:4ec819c96ec8627238505f',
    messagingSenderId: '170567973902',
    projectId: 'hallo-611ac',
    authDomain: 'hallo-611ac.firebaseapp.com',
    storageBucket: 'hallo-611ac.firebasestorage.app',
  );
}
